import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Matkollen App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav className="sticy top-0 px-2 py-4">
          <ul className="flex flex-row items-start gap-2 whitespace-nowrap">
              <Link href="/landingpage">LOG IN</Link>
              <Link href="/home">HOME</Link>
          </ul>
        </nav>
      </header>
          {children}
      </body>
    </html>
  )
}
