DROP TABLE IF EXISTS "livsmedel";
CREATE TABLE "public"."livsmedel" (
                                      "livsmedelsnamn" character varying(100),
                                      "livsmedelsnummer" character varying(100),
                                      "gruppering" character varying(100),
                                      "energi_kcal" character varying(100),
                                      "energi_kj" character varying(100),
                                      "fett_totalt_g" character varying(100),
                                      "protein_g" character varying(100),
                                      "kolhydrater_g" character varying(100),
                                      "fibrer_g" character varying(100),
                                      "vatten_g" character varying(100),
                                      "alkohol_g" character varying(100),
                                      "aska_g" character varying(100),
                                      "sockerarter_g" character varying(100),
                                      "monosackarider_g" character varying(100),
                                      "disackarider_g" character varying(100),
                                      "tillsatt_socker_g" character varying(100),
                                      "fritt_socker_g" character varying(100),
                                      "fullkorn_totalt_g" character varying(100),
                                      "summa_mättade_fettsyror_g" character varying(100),
                                      "fettsyra_g" character varying(100),
                                      "laurinsyra_g" character varying(100),
                                      "myristinsyra_g" character varying(100),
                                      "palmitinsyra_g" character varying(100),
                                      "stearinsyra_g" character varying(100),
                                      "arakidinsyra_g" character varying(100),
                                      "summa_enkelomättade_fettsyror_g" character varying(100),
                                      "palmitoljesyra_g" character varying(100),
                                      "oljesyra_g" character varying(100),
                                      "summa_fleromättade_fettsyror_g" character varying(100),
                                      "linolsyra_g" character varying(100),
                                      "linolensyra_g" character varying(100),
                                      "arakidonsyra_g" character varying(100),
                                      "epa_g" character varying(100),
                                      "dpa_g" character varying(100),
                                      "dha_g" character varying(100),
                                      "kolesterol_mg" character varying(100),
                                      "vitamin_a" character varying(100),
                                      "retinol" character varying(100),
                                      "betakaroten" character varying(100),
                                      "vitamin_d" character varying(100),
                                      "vitamin_e" character varying(100),
                                      "vitamin_k" character varying(100),
                                      "tiamin_mg" character varying(100),
                                      "riboflavin_mg" character varying(100),
                                      "niacin_mg" character varying(100),
                                      "niacinekvivalenter" character varying(100),
                                      "vitamin_b6" character varying(100),
                                      "folat" character varying(100),
                                      "vitamin_b12" character varying(100),
                                      "vitamin_c" character varying(100),
                                      "fosfor_mg" character varying(100),
                                      "jod" character varying(100),
                                      "järn_mg" character varying(100),
                                      "kalcium_mg" character varying(100),
                                      "kalium_mg" character varying(100),
                                      "magnesium_mg" character varying(100),
                                      "natrium_mg" character varying(100),
                                      "salt_g" character varying(100),
                                      "selen" character varying(100),
                                      "zink_mg" character varying(100),
                                      "avfall" character varying(100)
) WITH (oids = false);

INSERT INTO "livsmedel" ("livsmedelsnamn", "livsmedelsnummer", "gruppering", "energi_kcal", "energi_kj", "fett_totalt_g", "protein_g", "kolhydrater_g", "fibrer_g", "vatten_g", "alkohol_g", "aska_g", "sockerarter_g", "monosackarider_g", "disackarider_g", "tillsatt_socker_g", "fritt_socker_g", "fullkorn_totalt_g", "summa_mättade_fettsyror_g", "fettsyra_g", "laurinsyra_g", "myristinsyra_g", "palmitinsyra_g", "stearinsyra_g", "arakidinsyra_g", "summa_enkelomättade_fettsyror_g", "palmitoljesyra_g", "oljesyra_g", "summa_fleromättade_fettsyror_g", "linolsyra_g", "linolensyra_g", "arakidonsyra_g", "epa_g", "dpa_g", "dha_g", "kolesterol_mg", "vitamin_a", "retinol", "betakaroten", "vitamin_d", "vitamin_e", "vitamin_k", "tiamin_mg", "riboflavin_mg", "niacin_mg", "niacinekvivalenter", "vitamin_b6", "folat", "vitamin_b12", "vitamin_c", "fosfor_mg", "jod", "järn_mg", "kalcium_mg", "kalium_mg", "magnesium_mg", "natrium_mg", "salt_g", "selen", "zink_mg", "avfall") VALUES
('Kokosfett',	'4',	'Fett, olja',	'884',	'3700',	'100',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'92',	'13',	'46.3',	'18.7',	'9.6',	'3',	'0',	'6',	'0',	'7.2',	'2',	'1.8',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'11',	'',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0',	'0'),
('Morotsjuice',	'301',	'Dryck',	'34',	'142',	'0.4',	'0.7',	'6.3',	'1',	'91',	'0',	'0.6',	'4.7',	'2.3',	'2.4',	'0',	'5',	'0',	'0.1',	'0',	'0',	'0',	'0.1',	'0',	'0',	'0',	'0',	'0',	'0.2',	'0.2',	'0',	'0',	'0',	'0',	'0',	'0',	'218.3',	'0',	'2620',	'0',	'1.4',	'',	'0.09',	'0.06',	'0.39',	'0.51',	'0.22',	'14',	'0',	'3.8',	'31',	'3',	'0.6',	'19',	'300',	'23',	'39',	'0.1',	'0.1',	'0.2',	'0'),
('Broccoli',	'325',	'Grönsaker, baljväxter, svamp',	'40',	'167',	'0.6',	'4.3',	'2.3',	'4',	'88.2',	'0',	'0.6',	'1.9',	'1.9',	'0',	'0',	'0',	'0',	'0.2',	'0',	'0',	'0',	'0.1',	'0',	'0',	'0.1',	'0',	'0.1',	'0.3',	'0.1',	'0.2',	'0',	'0',	'0',	'0',	'0',	'48.4',	'0',	'578',	'0',	'1.6',	'101.6',	'0.15',	'0.12',	'0.8',	'1.5',	'0.13',	'95',	'0',	'79',	'81',	'2',	'1.1',	'48',	'397',	'22',	'9',	'0',	'1',	'0.7',	'39'),
